FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Копируем файлы проектов с сохранением структуры
COPY ["YPractice.slnx", "./"]
COPY ["Bookings/Bookings.Presentation/Bookings.Presentation.csproj", "src/Bookings/Bookings.Presentation/"]
COPY ["Bookings/Bookings.Application/Bookings.Application.csproj", "src/Bookings/Bookings.Application/"]
COPY ["Bookings/Bookings.Domain/Bookings.Domain.csproj", "src/Bookings/Bookings.Domain/"]
COPY ["Bookings/Bookings.Infrastructure/Bookings.Infrastructure.csproj", "src/Bookings/Bookings.Infrastructure/"]

RUN dotnet restore "src/Bookings/Bookings.Presentation/Bookings.Presentation.csproj"
COPY . .

WORKDIR "/src/Bookings/Bookings.Presentation"
RUN dotnet publish "Bookings.Presentation.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Bookings.Presentation.csproj.dll"]