FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Bookings/Bookings.Presentation/Bookings.Presentation.csproj", "Bookings/Bookings.Presentation/"]
COPY ["Common/CommonMiddleware/CommonMiddleware.csproj", "Common/CommonMiddleware/"]
COPY ["Common/CommonServiceCollectionExtensions/CommonServiceCollectionExtensions.csproj", "Common/CommonServiceCollectionExtensions/"]
COPY ["Bookings/Bookings.Application/Bookings.Application.csproj", "Bookings/Bookings.Application/"]
COPY ["Common/Contracts/Contracts.csproj", "Common/Contracts/"]
COPY ["Common/DateTimeProvider/DateTimeProvider.Abstractions/DateTimeManager.Abstractions.csproj", "Common/DateTimeProvider/DateTimeProvider.Abstractions/"]
COPY ["Common/TransactionManager/TransactionManager.Abstractions/TransactionManager.Abstractions.csproj", "Common/TransactionManager/TransactionManager.Abstractions/"]
COPY ["Common/UserRooles/UserRooles.csproj", "Common/UserRooles/"]
COPY ["Bookings/Bookings.Domain/Bookings.Domain.csproj", "Bookings/Bookings.Domain/"]
COPY ["Bookings/Bookings.Infrastructure/Bookings.Infrastructure.csproj", "Bookings/Bookings.Infrastructure/"]
COPY ["Common/DateTimeProvider/DateTimeProvider.Core/DateTimeManager.Core.csproj", "Common/DateTimeProvider/DateTimeProvider.Core/"]
COPY ["Common/TransactionManager/TransactionManager.Core/TransactionManager.Core.csproj", "Common/TransactionManager/TransactionManager.Core/"]
RUN dotnet restore "./Bookings/Bookings.Presentation/Bookings.Presentation.csproj"
COPY . .
WORKDIR "/src/Bookings/Bookings.Presentation"
RUN dotnet build "./Bookings.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Bookings.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Bookings.Presentation.dll"]