{
 "title": "Bookings",
 "description": "Сервис бронирований",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests per second" } },
   "targets": [
    {
     "expr": "sum by (http_route)(rate(http_server_request_duration_seconds_count{job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_process_memory_working_set_bytes{job=\"bookings-service\"})",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collections_total{job=\"bookings-service\", gc_heap_generation=\"gen0\"}[$__rate_interval]))",
     "legendFormat": "gen0"
    },
    {
     "expr": "sum(rate(dotnet_gc_collections_total{job=\"bookings-service\", gc_heap_generation=\"gen1\"}[$__rate_interval]))",
     "legendFormat": "gen1"
    },
    {
     "expr": "sum(rate(dotnet_gc_collections_total{job=\"bookings-service\", gc_heap_generation=\"gen2\"}[$__rate_interval]))",
     "legendFormat": "gen2"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count{job=\"bookings-service\", http_route=~\".*Bookings.*\"}[$__rate_interval])) * 100 ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(dotnet_process_cpu_time_seconds_total{job=\"bookings-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=\"bookings-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread pool length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(dotnet_thread_pool_queue_length{job=\"bookins-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(dotnet_thread_pool_work_item_count_total{job=\"bookings-service\"}[$__rate_interval]))",
     "legendFormat": "WorkItems"
    }
   ]
  }
 ]
}